### ISSUE TITLE
Can you run APK correctly?

### ISSUE THREAD

**Issue by rainyt** [altef/heaps-android#1]

**Comment by altef** [comment]
I could! Or, well, my phone could, I guess. Could you provide some context as to the issue you're facing?

**Comment by rainyt** [comment]
> 

The current situation is that APK can run, but there may be problems on some phone models. I will investigate this problem today.

**Comment by rainyt** [comment]
https://github.com/rainyt/zyheaps

Hi, these are some of my achievements. It has the ability to compile heaps Android targets

**Comment by rainyt** [comment]
@altef Hello, Do you know how Android dynamically loads resources?

**Comment by rainyt** [comment]
Fixed.

**Comment by altef** [comment]
Sorry, I'm not sure why I didn't see of the messages between between my reply on June 28th and your comment today. I definitely wasn't intentionally ignoring you!

**Comment by rainyt** [comment]
It doesn't matter. Do you know how to compile LibUv in CMakeList?
Because the new version of heaps seems to need a uv library to run properly.

**Comment by altef** [comment]
not off the top of my head, sorry!
